### PR TITLE
Stats tests molling

### PR DESCRIPTION
**Pull request by dmolling**
Mostly adding descriptive text for when to use the stats tests

### CODE REVIEW

**Review by nsbatra — DISMISSED** [review]
Thanks Daniel!

**Comment by nsbatra** [comment]
@dmolling  just so I can plan - will you have any edits for the regression page this week?

**Comment by dmolling** [comment]
I don't think so--I started my new position and have been much busier than expected. I think the content is good, but similarly could use more explanation and perhaps a quick introduction of lm for linear models before diving into glm

**Comment by nsbatra** [comment]
OK thanks for the time you did spare! Excited to hear that you have started
your new job.
Is there a hyperlink you want for your name in the Author acknowledgement
section? (linkedin, github, twitter?)

**Comment by dmolling** [comment]
Sure, maybe just my linkedin: https://www.linkedin.com/in/daniel-molling-4005716a/

**Pull request merged**
