### PR TITLE
Update importing.Rmd

### PR DESCRIPTION
**Pull request by henryls1**
faster way to import files from github - may apply to shp files as well

### CODE REVIEW

**Review by nsbatra — COMMENTED** [review]
Thanks for looking at this page, but I'll admit I'm a bit confused by this PR.... When I look in Github data folder at an xlsx file, I don't see a "Raw" option like I do for csv files. Instead I see "View raw" and "Download" (both of which do the same thing - open a download window). Is this the same for you? 
This is why the sentence above these bullets says "you may not be able to view the Raw data for some files..."

**Comment by henryls1** [comment]
Sorry if this is unclear - this is the link i was referring to: 

image

**Comment by henryls1** [comment]
I agree with bundling the data into a package as well - maybe we could have the html doc on it as well.

**Comment by nsbatra** [comment]
Thanks Henry. I've incorporated this in another branch.

**Pull request closed without merging**
